spring:
  application:
    name: project-one-ms-account
  #config:
    #import: configserver:http://localhost:8888

  #profiles:
    #active: dev
  data:
    mongodb:
      uri: mongodb+srv://dvivasva:admin23@everis.xiybt.mongodb.net/project-one
      #uri: ${mongodb.uri}
server:
  port: 8089
