spring:
  application:
    name: project-ms-one-account
  data:
    mongodb:
      uri: mongodb+srv://dvivasva:admin23@everis.xiybt.mongodb.net/project-one?retryWrites=true&w=majority

server:
  port: 8089